#!/bin/bash

if ! type "forever" > /dev/null; then
  echo "Running the tests requires `forever` to be installed.\nUse `npm install -g forever` to install it."
  exit 1
fi
forever start tests/server/server.js
python -m unittest discover tests '*_test.py'
forever stop tests/server/server.js
